services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # Environment variables can be added here if needed, e.g., for a different database
    # environment:
    #   DATABASE_URL: "file:/data/prod.db" # Already set in schema, but could override
    restart: unless-stopped
