services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
    environment:
      DATABASE_URL: "file:./prisma/dev.db"
    restart: unless-stopped
